Repository ctolon/PythonInterfaceOOP, pull requests merged in 2022-11, with the labels that each got.

#16 Implement new configurbles in TableReader + rename some process funct…
  configs/configAnalysisData.json
  dqtasks/dqEfficiency.py
  dqtasks/tableReader.py
  runTableReader.py
Labels: enhancement, maintaince

#18 Scripts to run the EM efficiency
  configs/configAnalysisMCEM.json
  configs/configAnalysisMCEMNoSkimmed.json
  dqtasks/emEfficiency.py
  dqtasks/emEfficiencyNoSkimmed.py
  runEMEfficiency.py
  runEMEfficiencyNotSkimmed.py
Labels: enhancement

#20 Latest Changes -> CLI Argument Impl
  dqtasks/tableReader.py
Labels: enhancement, maintaince

#21 memory optimization and duplicated misnamed option removed from json
  configs/configAnalysisMCEM.json
  runEMEfficiency.py
Labels: bug, maintaince
